baseURL = "http://www.mchange.com/projects/ens-scala/"
languageCode = "en-us"
title = "ens-scala"
theme = "hugo-theme-docdock"

[params]
   noSearch   = "true"
#   noHomeIcon = "true"

[[menu.shortcuts]]
pre="<div class=\"more\">more &rarr;</div>"
name = "API Documentation"
identifier = "hugodoc-api"
url = "/latest/api/com/mchange/sc/v2/ens/"
weight = 50


